### PR TITLE
Update to specs 0.14

### PR DESCRIPTION
**Pull request by LaylBongers**
While I haven't extensively tested this, the unit tests pass.

---
This change is [Reviewable](https://reviewable.io/reviews/rustgd/specs-hierarchy/8)

### CODE REVIEW

**Review by torkleyy — APPROVED** [review]
Awesome, thank you! This doesn't utilize the new `FlaggedStorage`, but it's a start.

**Comment by LaylBongers** [comment]
I feel like any functionality changes are out of scope of this PR, this is simply a straight update to the new version.

**Comment by torkleyy** [comment]
:+1: I just waited for other reviews, but there are none, so let's merge this!

bors r+

**Comment by torkleyy** [comment]
Published ;)

**Pull request merged**
